# Site settings
title: Bradley Gorski
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  /BradleyGorski/
url:  https://bradleygorski.github.io/
twitter_username: bradleygorski
github_username:  bradleygorski

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


